    version: '3.8'
    services:
      db:
        image: postgres:latest
        restart: always
        environment:
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
          - ./init-scripts:/docker-entrypoint-initdb.d
          - pgdata:/var/lib/postgresql/data
        ports:
          - "5432:5432"
    volumes:
      pgdata: